/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorObject } from '../models/errorObject.js';

/**
 * Creates an instance of GeolocationV1Geolocate404
 */
interface GeolocationV1Geolocate404 {
  error: ErrorObject;
  additionalProperties?: Record<string, unknown>;
}

export class GeolocationV1Geolocate404Error extends ApiError<
  GeolocationV1Geolocate404
> {}
