/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorObject } from '../models/errorObject.js';

/**
 * Creates an instance of GeolocationV1Geolocate400
 */
interface GeolocationV1Geolocate400 {
  error: ErrorObject;
  additionalProperties?: Record<string, unknown>;
}

export class GeolocationV1Geolocate400Error extends ApiError<
  GeolocationV1Geolocate400
> {}
