/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { NearestRoadsError } from '../models/nearestRoadsError.js';

/**
 * Creates an instance of V1NearestRoads400
 */
interface V1NearestRoads400 {
  error?: NearestRoadsError;
  additionalProperties?: Record<string, unknown>;
}

export class V1NearestRoads400Error extends ApiError<V1NearestRoads400> {}
