/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GeolocationV1GeolocateRequest,
  geolocationV1GeolocateRequestSchema,
} from '../models/geolocationV1GeolocateRequest.js';
import {
  GeolocationV1GeolocateResponse,
  geolocationV1GeolocateResponseSchema,
} from '../models/geolocationV1GeolocateResponse.js';
import { optional } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { GeolocationV1Geolocate400Error } from '../errors/geolocationV1Geolocate400Error.js';
import { GeolocationV1Geolocate404Error } from '../errors/geolocationV1Geolocate404Error.js';

export class GeolocationApi extends BaseApi {
  /**
   * Geolocation API returns a location and accuracy radius based on information about cell towers and
   * WiFi nodes that the mobile client can detect. This document describes the protocol used to send this
   * data to the server and to return a response to the client.
   *
   * Communication is done over HTTPS using POST. Both request and response are formatted as JSON, and
   * the content type of both is `application/json`.
   *
   * You must specify a key in your request, included as the value of a`key` parameter. A `key` is your
   * application's  API key. This key identifies your application for purposes of quota management. Learn
   * how to [get a key](https://developers.google.com/maps/documentation/geolocation/get-api-key).
   *
   * @param body         The request body must be formatted as JSON.
   * @return Response from the API call
   */
  async geolocate(
    body?: GeolocationV1GeolocateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GeolocationV1GeolocateResponse>> {
    const req = this.createRequest('POST', '/geolocation/v1/geolocate');
    const mapped = req.prepareArgs({
      body: [body, optional(geolocationV1GeolocateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, GeolocationV1Geolocate400Error, '400 BAD REQUEST');
    req.throwOn(404, GeolocationV1Geolocate404Error, '404 NOT FOUND');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(geolocationV1GeolocateResponseSchema, requestOptions);
  }
}
