/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  NearestRoadsResponse,
  nearestRoadsResponseSchema,
} from '../models/nearestRoadsResponse.js';
import {
  SnapToRoadsResponse,
  snapToRoadsResponseSchema,
} from '../models/snapToRoadsResponse.js';
import { array, boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { V1NearestRoads400Error } from '../errors/v1NearestRoads400Error.js';

export class RoadsApi extends BaseApi {
  /**
   * This service returns the best-fit road geometry for a given set of GPS coordinates. This service
   * takes up to 100 GPS points collected along a route, and returns a similar set of data with the
   * points snapped to the most likely roads the vehicle was traveling along. Optionally, you can request
   * that the points be interpolated, resulting in a path that smoothly follows the geometry of the road.
   *
   * @param path        The path to be snapped. The path parameter accepts a list of latitude/longitude
   *                                pairs. Latitude and longitude values should be separated by commas. Coordinates
   *                                should be separated by the pipe character: "|". For example: `path=60.170880,24.
   *                                942795|60.170879,24.942796|60.170877,24.942796`. <div class="note">Note: The
   *                                snapping algorithm works best for points that are not too far apart. If you observe
   *                                odd snapping behavior, try creating paths that have points closer together. To
   *                                ensure the best snap-to-road quality, you should aim to provide paths on which
   *                                consecutive pairs of points are within 300m of each other. This will also help in
   *                                handling any isolated, long jumps between consecutive points caused by GPS signal
   *                                loss, or noise.</div>
   * @param interpolate Whether to interpolate a path to include all points forming the full road-geometry.
   *                                When true, additional interpolated points will also be returned, resulting in a
   *                                path that smoothly follows the geometry of the road, even around corners and
   *                                through tunnels. Interpolated paths will most likely contain more points than the
   *                                original path. Defaults to `false`.
   * @return Response from the API call
   */
  async snapToRoads(
    path: string[],
    interpolate?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SnapToRoadsResponse>> {
    const req = this.createRequest('GET', '/v1/snaptoroads');
    const mapped = req.prepareArgs({
      path: [path, array(string())],
      interpolate: [interpolate, optional(boolean())],
    });
    req.query('path', mapped.path);
    req.query('interpolate', mapped.interpolate);
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(snapToRoadsResponseSchema, requestOptions);
  }

  /**
   * This service returns individual road segments for a given set of GPS coordinates. This services
   * takes up to 100 GPS points and returns the closest road segments for each point. The points passed
   * do not need to be part of a continuous path.
   *
   * @param points The points to be snapped. The points parameter accepts a list of latitude/longitude
   *                           pairs. Separate latitude and longitude values with commas. Separate coordinates with the
   *                           pipe character: "|". For example: `points=60.170880,24.942795|60.170879,24.942796|60.
   *                           170877,24.942796`.
   * @return Response from the API call
   */
  async nearestRoads(
    points: string[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NearestRoadsResponse>> {
    const req = this.createRequest('GET', '/v1/nearestRoads');
    const mapped = req.prepareArgs({ points: [points, array(string())] });
    req.query('points', mapped.points);
    req.throwOn(400, V1NearestRoads400Error, '400 BAD REQUEST');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(nearestRoadsResponseSchema, requestOptions);
  }
}
