/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Source1, source1Schema } from '../models/source1.js';
import {
  StreetViewResponse,
  streetViewResponseSchema,
} from '../models/streetViewResponse.js';
import { boolean, number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class StreetViewApi extends BaseApi {
  /**
   * The Street View Static API lets you embed a static (non-interactive) Street View panorama or
   * thumbnail into your web page, without the use of JavaScript. The viewport is defined with URL
   * parameters sent through a standard HTTP request, and is returned as a static image.
   *
   *
   * @param size              Specifies the output size of the image in pixels. Must not exceed 640 pixels
   *                                     wide or high, anything over will default to 640 pixels. Size is specified as
   *                                     `{width}x{height}` - for example, `size=600x400` returns an image 600 pixels
   *                                     wide, and 400 high.
   * @param fov               Determines the horizontal field of view of the image. The field of view is
   *                                     expressed in degrees, with a maximum allowed value of 120. When dealing with a
   *                                     fixed-size viewport, as with a Street View image of a set size, field of view
   *                                     in essence represents zoom, with smaller numbers indicating a higher level of
   *                                     zoom. Default is 90.
   * @param heading           Indicates the compass heading of the camera. Accepted values are from 0 to
   *                                     360 (both values indicating North, with 90 indicating East, and 180 South). If
   *                                     no heading is specified, a value will be calculated that directs the camera
   *                                     towards the specified location, from the point at which the closest photograph
   *                                     was taken.
   * @param location          The point around which to retrieve place information. The Street View Static
   *                                     API will snap to the panorama photographed closest to this location. When an
   *                                     address text string is provided, the API may use a different camera location
   *                                     to better display the specified location. When a lat/lng is provided, the API
   *                                     searches a 50 meter radius for a photograph closest to this location. Because
   *                                     Street View imagery is periodically refreshed, and photographs may be taken
   *                                     from slightly different positions each time, it's possible that your
   *                                     `location` may snap to a different panorama when imagery is updated.
   * @param pano              A specific panorama ID. These are generally stable, though panoramas may
   *                                     change ID over time as imagery is refreshed.
   * @param pitch             Specifies the up or down angle of the camera relative to the Street View
   *                                     vehicle. This is often, but not always, flat horizontal. Positive values angle
   *                                     the camera up (with 90 degrees indicating straight up); negative values angle
   *                                     the camera down (with -90 indicating straight down). Default is 0.
   * @param radius            Sets a radius, specified in meters, in which to search for a panorama,
   *                                     centered on the given latitude and longitude. Valid values are non-negative
   *                                     integers. Default is 50 meters.
   * @param returnErrorCode   Indicates whether the API should return a non `200 Ok` HTTP status when no
   *                                     image is found (`404 NOT FOUND`), or in response to an invalid request (400
   *                                     BAD REQUEST). Valid values are `true` and `false`. If set to `true`, an error
   *                                     message is returned in place of the generic gray image. This eliminates the
   *                                     need to make a separate call to check for image availability.
   * @param signature         A digital signature used to verify that any site generating requests using
   *                                     your API key is authorized to do so. Requests that do not include a digital
   *                                     signature might fail. For more information, see [Get a Key and
   *                                     Signature](https://developers.google.com/maps/documentation/streetview/get-api-
   *                                     key).
   * @param source            Limits Street View searches to selected sources. Valid values are: *
   *                                     `default` uses the default sources for Street View; searches are not limited
   *                                     to specific sources. * `outdoor` limits searches to outdoor collections.
   *                                     Indoor collections are not included in search results. Note that outdoor
   *                                     panoramas may not exist for the specified location. Also note that the search
   *                                     only returns panoramas where it's possible to determine whether they're
   *                                     indoors or outdoors. For example, PhotoSpheres are not returned because it's
   *                                     unknown whether they are indoors or outdoors.
   * @return Response from the API call
   */
  async streetView(
    size: string,
    fov?: number,
    heading?: number,
    location?: string,
    pano?: string,
    pitch?: number,
    radius?: number,
    returnErrorCode?: boolean,
    signature?: string,
    source?: Source1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/maps/api/streetview');
    const mapped = req.prepareArgs({
      size: [size, string()],
      fov: [fov, optional(number())],
      heading: [heading, optional(number())],
      location: [location, optional(string())],
      pano: [pano, optional(string())],
      pitch: [pitch, optional(number())],
      radius: [radius, optional(number())],
      returnErrorCode: [returnErrorCode, optional(boolean())],
      signature: [signature, optional(string())],
      source: [source, optional(source1Schema)],
    });
    req.query('size', mapped.size);
    req.query('fov', mapped.fov);
    req.query('heading', mapped.heading);
    req.query('location', mapped.location);
    req.query('pano', mapped.pano);
    req.query('pitch', mapped.pitch);
    req.query('radius', mapped.radius);
    req.query('return_error_code', mapped.returnErrorCode);
    req.query('signature', mapped.signature);
    req.query('source', mapped.source);
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * The Street View Static API metadata requests provide data about Street View panoramas. Using the
   * metadata, you can find out if a Street View image is available at a given location, as well as
   * getting programmatic access to the latitude and longitude, the panorama ID, the date the photo was
   * taken, and the copyright information for the image. Accessing this metadata allows you to customize
   * error behavior in your application.
   *
   *
   * @param heading           Indicates the compass heading of the camera. Accepted values are from 0 to
   *                                     360 (both values indicating North, with 90 indicating East, and 180 South). If
   *                                     no heading is specified, a value will be calculated that directs the camera
   *                                     towards the specified location, from the point at which the closest photograph
   *                                     was taken.
   * @param location          The point around which to retrieve place information. The Street View Static
   *                                     API will snap to the panorama photographed closest to this location. When an
   *                                     address text string is provided, the API may use a different camera location
   *                                     to better display the specified location. When a lat/lng is provided, the API
   *                                     searches a 50 meter radius for a photograph closest to this location. Because
   *                                     Street View imagery is periodically refreshed, and photographs may be taken
   *                                     from slightly different positions each time, it's possible that your
   *                                     `location` may snap to a different panorama when imagery is updated.
   * @param pano              A specific panorama ID. These are generally stable, though panoramas may
   *                                     change ID over time as imagery is refreshed.
   * @param pitch             Specifies the up or down angle of the camera relative to the Street View
   *                                     vehicle. This is often, but not always, flat horizontal. Positive values angle
   *                                     the camera up (with 90 degrees indicating straight up); negative values angle
   *                                     the camera down (with -90 indicating straight down). Default is 0.
   * @param radius            Sets a radius, specified in meters, in which to search for a panorama,
   *                                     centered on the given latitude and longitude. Valid values are non-negative
   *                                     integers. Default is 50 meters.
   * @param returnErrorCode   Indicates whether the API should return a non `200 Ok` HTTP status when no
   *                                     image is found (`404 NOT FOUND`), or in response to an invalid request (400
   *                                     BAD REQUEST). Valid values are `true` and `false`. If set to `true`, an error
   *                                     message is returned in place of the generic gray image. This eliminates the
   *                                     need to make a separate call to check for image availability.
   * @param signature         A digital signature used to verify that any site generating requests using
   *                                     your API key is authorized to do so. Requests that do not include a digital
   *                                     signature might fail. For more information, see [Get a Key and
   *                                     Signature](https://developers.google.com/maps/documentation/streetview/get-api-
   *                                     key).
   * @param size              Specifies the output size of the image in pixels. Size is specified as
   *                                     `{width}x{height}` - for example, `size=600x400` returns an image 600 pixels
   *                                     wide, and 400 high.
   * @param source            Limits Street View searches to selected sources. Valid values are: *
   *                                     `default` uses the default sources for Street View; searches are not limited
   *                                     to specific sources. * `outdoor` limits searches to outdoor collections.
   *                                     Indoor collections are not included in search results. Note that outdoor
   *                                     panoramas may not exist for the specified location. Also note that the search
   *                                     only returns panoramas where it's possible to determine whether they're
   *                                     indoors or outdoors. For example, PhotoSpheres are not returned because it's
   *                                     unknown whether they are indoors or outdoors.
   * @return Response from the API call
   */
  async streetViewMetadata(
    heading?: number,
    location?: string,
    pano?: string,
    pitch?: number,
    radius?: number,
    returnErrorCode?: boolean,
    signature?: string,
    size?: string,
    source?: Source1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<StreetViewResponse>> {
    const req = this.createRequest('GET', '/maps/api/streetview/metadata');
    const mapped = req.prepareArgs({
      heading: [heading, optional(number())],
      location: [location, optional(string())],
      pano: [pano, optional(string())],
      pitch: [pitch, optional(number())],
      radius: [radius, optional(number())],
      returnErrorCode: [returnErrorCode, optional(boolean())],
      signature: [signature, optional(string())],
      size: [size, optional(string())],
      source: [source, optional(source1Schema)],
    });
    req.query('heading', mapped.heading);
    req.query('location', mapped.location);
    req.query('pano', mapped.pano);
    req.query('pitch', mapped.pitch);
    req.query('radius', mapped.radius);
    req.query('return_error_code', mapped.returnErrorCode);
    req.query('signature', mapped.signature);
    req.query('size', mapped.size);
    req.query('source', mapped.source);
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(streetViewResponseSchema, requestOptions);
  }
}
