/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Language1, language1Schema } from '../models/language1.js';
import {
  TimeZoneResponse,
  timeZoneResponseSchema,
} from '../models/timeZoneResponse.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TimeZoneApi extends BaseApi {
  /**
   * The Time Zone API provides a simple interface to request the time zone for locations on the surface
   * of the earth, as well as the time offset from UTC for each of those locations. You request the time
   * zone information for a specific latitude/longitude pair and date. The API returns the name of that
   * time zone, the time offset from UTC, and the daylight savings offset.
   *
   *
   * @param location  A comma-separated latitude,longitude tuple, `location=39.6034810,-119.6822510`,
   *                               representing the location to look up.
   * @param timestamp The desired time as seconds since midnight, January 1, 1970 UTC. The Time Zone API
   *                               uses the `timestamp` to determine whether or not Daylight Savings should be applied,
   *                               based on the time zone of the `location`.   Note that the API does not take
   *                               historical time zones into account. That is, if you specify a past timestamp, the
   *                               API does not take into account the possibility that the location was previously in a
   *                               different time zone.
   * @param language  The language in which to return results.  * See the [list of supported
   *                               languages](https://developers.google.com/maps/faq#languagesupport). Google often
   *                               updates the supported languages, so this list may not be exhaustive. * If `language`
   *                               is not supplied, the API attempts to use the preferred language as specified in the
   *                               `Accept-Language` header. * The API does its best to provide a street address that
   *                               is readable for both the user and locals. To achieve that goal, it returns street
   *                               addresses in the local language, transliterated to a script readable by the user if
   *                               necessary, observing the preferred language. All other addresses are returned in the
   *                               preferred language. Address components are all returned in the same language, which
   *                               is chosen from the first component. * If a name is not available in the preferred
   *                               language, the API uses the closest match. * The preferred language has a small
   *                               influence on the set of results that the API chooses to return, and the order in
   *                               which they are returned. The geocoder interprets abbreviations differently depending
   *                               on language, such as the abbreviations for street types, or synonyms that may be
   *                               valid in one language but not in another. For example, _utca_ and _tér_ are synonyms
   *                               for street in Hungarian.
   * @return Response from the API call
   */
  async timezone(
    location: string,
    timestamp: number,
    language?: Language1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TimeZoneResponse>> {
    const req = this.createRequest('GET', '/maps/api/timezone/json');
    const mapped = req.prepareArgs({
      location: [location, string()],
      timestamp: [timestamp, number()],
      language: [language, optional(language1Schema)],
    });
    req.query('location', mapped.location);
    req.query('timestamp', mapped.timestamp);
    req.query('language', mapped.language);
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(timeZoneResponseSchema, requestOptions);
  }
}
