/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AddressComponent {
  /** The full text description or name of the address component as returned by the Geocoder. */
  longName: string;
  /** An abbreviated textual name for the address component, if available. For example, an address component for the state of Alaska may have a long_name of "Alaska" and a short_name of "AK" using the 2-letter postal abbreviation. */
  shortName: string;
  /** An array indicating the type of the address component. See the list of [supported types](https://developers.google.com/maps/documentation/places/web-service/supported_types). */
  types: string[];
  additionalProperties?: Record<string, unknown>;
}

export const addressComponentSchema: Schema<AddressComponent> = typedExpandoObject(
  {
    longName: ['long_name', string()],
    shortName: ['short_name', string()],
    types: ['types', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
