/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AreaType
 */
export enum AreaType {
  AdministrativeAreaLevel1 = 'administrative_area_level_1',
  AdministrativeAreaLevel2 = 'administrative_area_level_2',
  AdministrativeAreaLevel3 = 'administrative_area_level_3',
  AdministrativeAreaLevel4 = 'administrative_area_level_4',
  AdministrativeAreaLevel5 = 'administrative_area_level_5',
  AmusementPark = 'amusement_park',
  Airport = 'airport',
  ColloquialArea = 'colloquial_area',
  Country = 'country',
  Establishment = 'establishment',
  Intersection = 'intersection',
  Locality = 'locality',
  NaturalFeature = 'natural_feature',
  Neighborhood = 'neighborhood',
  Park = 'park',
  PlusCode = 'plus_code',
  PointOfInterest = 'point_of_interest',
  Political = 'political',
  PostalCode = 'postal_code',
  Premise = 'premise',
  Route = 'route',
  StreetAddress = 'street_address',
  Sublocality = 'sublocality',
  SublocalityLevel1 = 'sublocality_level_1',
  Subpremise = 'subpremise',
  TouristAttraction = 'tourist_attraction',
  TrainStation = 'train_station',
  TransitStation = 'transit_station',
}

/**
 * Schema for AreaType
 */
export const areaTypeSchema: Schema<AreaType> = stringEnum(AreaType);
