/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Northeast, northeastSchema } from './northeast.js';
import { Southwest, southwestSchema } from './southwest.js';

export interface Bounds1 {
  northeast: Northeast;
  southwest: Southwest;
  additionalProperties?: Record<string, unknown>;
}

export const bounds1Schema: Schema<Bounds1> = lazy(() =>
  typedExpandoObject(
    {
      northeast: ['northeast', northeastSchema],
      southwest: ['southwest', southwestSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
