/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BusinessStatus
 */
export enum BusinessStatus {
  Operational = 'OPERATIONAL',
  ClosedTemporarily = 'CLOSED_TEMPORARILY',
  ClosedPermanently = 'CLOSED_PERMANENTLY',
}

/**
 * Schema for BusinessStatus
 */
export const businessStatusSchema: Schema<BusinessStatus> = stringEnum(
  BusinessStatus
);
