/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ArrivalTime, arrivalTimeSchema } from './arrivalTime.js';
import { DepartureTime, departureTimeSchema } from './departureTime.js';
import { DirectionsStep, directionsStepSchema } from './directionsStep.js';
import {
  DirectionsTrafficSpeedEntry,
  directionsTrafficSpeedEntrySchema,
} from './directionsTrafficSpeedEntry.js';
import {
  DirectionsViaWaypoint,
  directionsViaWaypointSchema,
} from './directionsViaWaypoint.js';
import { Distance, distanceSchema } from './distance.js';
import { Duration, durationSchema } from './duration.js';
import {
  DurationInTraffic,
  durationInTrafficSchema,
} from './durationInTraffic.js';
import { EndLocation, endLocationSchema } from './endLocation.js';
import { StartLocation, startLocationSchema } from './startLocation.js';

export interface DirectionsLeg {
  arrivalTime?: ArrivalTime;
  departureTime?: DepartureTime;
  distance?: Distance;
  duration?: Duration;
  durationInTraffic?: DurationInTraffic;
  /** Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  endAddress: string;
  endLocation: EndLocation;
  /** Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  startAddress: string;
  startLocation: StartLocation;
  /** An array of steps denoting information about each separate step of the leg of the journey. */
  steps: DirectionsStep[];
  /** Information about traffic speed along the leg. */
  trafficSpeedEntry: DirectionsTrafficSpeedEntry[];
  /** The locations of via waypoints along this leg. */
  viaWaypoint: DirectionsViaWaypoint[];
  additionalProperties?: Record<string, unknown>;
}

export const directionsLegSchema: Schema<DirectionsLeg> = lazy(() =>
  typedExpandoObject(
    {
      arrivalTime: ['arrival_time', optional(arrivalTimeSchema)],
      departureTime: ['departure_time', optional(departureTimeSchema)],
      distance: ['distance', optional(distanceSchema)],
      duration: ['duration', optional(durationSchema)],
      durationInTraffic: [
        'duration_in_traffic',
        optional(durationInTrafficSchema),
      ],
      endAddress: ['end_address', string()],
      endLocation: ['end_location', endLocationSchema],
      startAddress: ['start_address', string()],
      startLocation: ['start_location', startLocationSchema],
      steps: ['steps', array(directionsStepSchema)],
      trafficSpeedEntry: [
        'traffic_speed_entry',
        array(directionsTrafficSpeedEntrySchema),
      ],
      viaWaypoint: ['via_waypoint', array(directionsViaWaypointSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
