/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ArrivalTime, arrivalTimeSchema } from './arrivalTime.js';
import { DepartureTime, departureTimeSchema } from './departureTime.js';
import {
  DirectionsTransitLine,
  directionsTransitLineSchema,
} from './directionsTransitLine.js';
import {
  DirectionsTransitStop,
  directionsTransitStopSchema,
} from './directionsTransitStop.js';

/** Additional information that is not relevant for other modes of transportation. */
export interface DirectionsTransitDetails {
  arrivalStop?: DirectionsTransitStop;
  arrivalTime?: ArrivalTime;
  departureStop?: DirectionsTransitStop;
  departureTime?: DepartureTime;
  /** Specifies the direction in which to travel on this line, as it is marked on the vehicle or at the departure stop. This will often be the terminus station. */
  headsign?: string;
  /** Specifies the expected number of seconds between departures from the same stop at this time. For example, with a `headway` value of 600, you would expect a ten minute wait if you should miss your bus. */
  headway?: number;
  line?: DirectionsTransitLine;
  /** The number of stops from the departure to the arrival stop. This includes the arrival stop, but not the departure stop. For example, if your directions involve leaving from Stop A, passing through stops B and C, and arriving at stop D, `num_stops` will return 3. */
  numStops?: number;
  /** The text that appears in schedules and sign boards to identify a transit trip to passengers. The text should uniquely identify a trip within a service day. For example, "538" is the `trip_short_name` of the Amtrak train that leaves San Jose, CA at 15:10 on weekdays to Sacramento, CA. */
  tripShortName?: string;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTransitDetailsSchema: Schema<DirectionsTransitDetails> = lazy(
  () =>
    typedExpandoObject(
      {
        arrivalStop: ['arrival_stop', optional(directionsTransitStopSchema)],
        arrivalTime: ['arrival_time', optional(arrivalTimeSchema)],
        departureStop: [
          'departure_stop',
          optional(directionsTransitStopSchema),
        ],
        departureTime: ['departure_time', optional(departureTimeSchema)],
        headsign: ['headsign', optional(string())],
        headway: ['headway', optional(number())],
        line: ['line', optional(directionsTransitLineSchema)],
        numStops: ['num_stops', optional(number())],
        tripShortName: ['trip_short_name', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
