/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DirectionsStatus
 */
export enum DirectionsStatus {
  Ok = 'OK',
  NotFound = 'NOT_FOUND',
  ZeroResults = 'ZERO_RESULTS',
  MaxWaypointsExceeded = 'MAX_WAYPOINTS_EXCEEDED',
  MaxRouteLengthExceeded = 'MAX_ROUTE_LENGTH_EXCEEDED',
  InvalidRequest = 'INVALID_REQUEST',
  OverDailyLimit = 'OVER_DAILY_LIMIT',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for DirectionsStatus
 */
export const directionsStatusSchema: Schema<DirectionsStatus> = stringEnum(
  DirectionsStatus
);
