/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Bounds1, bounds1Schema } from './bounds1.js';
import { DirectionsLeg, directionsLegSchema } from './directionsLeg.js';
import { Fare1, fare1Schema } from './fare1.js';
import {
  OverviewPolyline,
  overviewPolylineSchema,
} from './overviewPolyline.js';

/** Routes consist of nested `legs` and `steps`. */
export interface DirectionsRoute {
  /** An array which contains information about a leg of the route, between two locations within the given route. A separate leg will be present for each waypoint or destination specified. (A route with no waypoints will contain exactly one leg within the legs array.) Each leg consists of a series of steps. */
  legs: DirectionsLeg[];
  bounds: Bounds1;
  /** Contains the copyright notices to be displayed for this route. You must handle and display this information yourself. This content is meant to be read as-is. Do not programmatically parse this display-only content. */
  copyrights: string;
  /** Contains a short textual description for the route, suitable for naming and disambiguating the route from alternatives. */
  summary: string;
  /** An array indicating the order of any waypoints in the calculated route. This waypoints may be reordered if the request was passed optimize:true within its waypoints parameter. */
  waypointOrder: number[];
  /** Contains an array of warnings to be displayed when showing these directions. You must handle and display these warnings yourself. */
  warnings: string[];
  overviewPolyline: OverviewPolyline;
  fare?: Fare1;
  additionalProperties?: Record<string, unknown>;
}

export const directionsRouteSchema: Schema<DirectionsRoute> = lazy(() =>
  typedExpandoObject(
    {
      legs: ['legs', array(directionsLegSchema)],
      bounds: ['bounds', bounds1Schema],
      copyrights: ['copyrights', string()],
      summary: ['summary', string()],
      waypointOrder: ['waypoint_order', array(number())],
      warnings: ['warnings', array(string())],
      overviewPolyline: ['overview_polyline', overviewPolylineSchema],
      fare: ['fare', optional(fare1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
