/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DirectionsTransitAgency {
  /** The name of this transit agency. */
  name?: string;
  /** The transit agency's phone number. */
  phone?: string;
  /** The transit agency's URL. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTransitAgencySchema: Schema<DirectionsTransitAgency> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    phone: ['phone', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
