/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DirectionsTransitAgency,
  directionsTransitAgencySchema,
} from './directionsTransitAgency.js';
import {
  DirectionsTransitVehicle,
  directionsTransitVehicleSchema,
} from './directionsTransitVehicle.js';

export interface DirectionsTransitLine {
  /** The transit agency (or agencies) that operates this transit line. */
  agencies: DirectionsTransitAgency[];
  /** The color commonly used in signage for this line. */
  color?: string;
  /** The full name of this transit line, e.g. "8 Avenue Local". */
  name: string;
  /** The short name of this transit line. This will normally be a line number, such as "M7" or "355". */
  shortName?: string;
  /** The color commonly used in signage for this line. */
  textColor?: string;
  /** Contains the URL for this transit line as provided by the transit agency. */
  url?: string;
  /** Contains the URL for the icon associated with this line. */
  icon?: string;
  vehicle?: DirectionsTransitVehicle;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTransitLineSchema: Schema<DirectionsTransitLine> = lazy(
  () =>
    typedExpandoObject(
      {
        agencies: ['agencies', array(directionsTransitAgencySchema)],
        color: ['color', optional(string())],
        name: ['name', string()],
        shortName: ['short_name', optional(string())],
        textColor: ['text_color', optional(string())],
        url: ['url', optional(string())],
        icon: ['icon', optional(string())],
        vehicle: ['vehicle', optional(directionsTransitVehicleSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
