/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Distance, distanceSchema } from './distance.js';
import { Duration, durationSchema } from './duration.js';
import { EndLocation, endLocationSchema } from './endLocation.js';
import { Maneuver, maneuverSchema } from './maneuver.js';
import { Polyline, polylineSchema } from './polyline.js';
import { StartLocation, startLocationSchema } from './startLocation.js';
import { TransitDetails, transitDetailsSchema } from './transitDetails.js';
import { TravelMode, travelModeSchema } from './travelMode.js';

/**
 * Each element in the steps array defines a single step of the calculated directions. A step is the most atomic unit of a direction's route, containing a single step describing a specific, single instruction on the journey. E.g. "Turn left at W. 4th St." The step not only describes the instruction but also contains distance and duration information relating to how this step relates to the following step. For example, a step denoted as "Merge onto I-80 West" may contain a duration of "37 miles" and "40 minutes," indicating that the next step is 37 miles/40 minutes from this step.
 * When using the Directions API to search for transit directions, the steps array will include additional transit details in the form of a transit_details array. If the directions include multiple modes of transportation, detailed directions will be provided for walking or driving steps in an inner steps array. For example, a walking step will include directions from the start and end locations: "Walk to Innes Ave & Fitch St". That step will include detailed walking directions for that route in the inner steps array, such as: "Head north-west", "Turn left onto Arelious Walker", and "Turn left onto Innes Ave".
 */
export interface DirectionsStep {
  distance?: Distance;
  duration: Duration;
  endLocation: EndLocation;
  /** Contains formatted instructions for this step, presented as an HTML text string. This content is meant to be read as-is. Do not programmatically parse this display-only content. */
  htmlInstructions: string;
  maneuver?: Maneuver;
  polyline: Polyline;
  startLocation: StartLocation;
  transitDetails?: TransitDetails;
  travelMode: TravelMode;
  /** Contains detailed directions for walking or driving steps in transit directions. Substeps are only available when travel_mode is set to "transit". The inner steps array is of the same type as steps. */
  steps?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const directionsStepSchema: Schema<DirectionsStep> = lazy(() =>
  typedExpandoObject(
    {
      distance: ['distance', optional(distanceSchema)],
      duration: ['duration', durationSchema],
      endLocation: ['end_location', endLocationSchema],
      htmlInstructions: ['html_instructions', string()],
      maneuver: ['maneuver', optional(maneuverSchema)],
      polyline: ['polyline', polylineSchema],
      startLocation: ['start_location', startLocationSchema],
      transitDetails: ['transit_details', optional(transitDetailsSchema)],
      travelMode: ['travel_mode', travelModeSchema],
      steps: ['steps', optional(unknown())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
