/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';

export interface DirectionsTransitStop {
  location: Location;
  /** The name of the transit stop. */
  name: string;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTransitStopSchema: Schema<DirectionsTransitStop> = lazy(
  () =>
    typedExpandoObject(
      { location: ['location', locationSchema], name: ['name', string()] },
      'additionalProperties',
      optional(unknown())
    )
);
