/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';

export interface DirectionsViaWaypoint {
  location?: Location;
  /** The index of the step containing the waypoint. */
  stepIndex?: number;
  /** The position of the waypoint along the step's polyline, expressed as a ratio from 0 to 1. */
  stepInterpolation?: number;
  additionalProperties?: Record<string, unknown>;
}

export const directionsViaWaypointSchema: Schema<DirectionsViaWaypoint> = lazy(
  () =>
    typedExpandoObject(
      {
        location: ['location', optional(locationSchema)],
        stepIndex: ['step_index', optional(number())],
        stepInterpolation: ['step_interpolation', optional(number())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
