/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { VehicleType, vehicleTypeSchema } from './vehicleType.js';

export interface DirectionsTransitVehicle {
  /** Contains the URL for an icon associated with this vehicle type. */
  icon?: string;
  /** Contains the URL for the icon associated with this vehicle type, based on the local transport signage. */
  localIcon?: string;
  /** The name of this vehicle, capitalized. */
  name: string;
  vehicleType?: VehicleType;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTransitVehicleSchema: Schema<DirectionsTransitVehicle> = typedExpandoObject(
  {
    icon: ['icon', optional(string())],
    localIcon: ['local_icon', optional(string())],
    name: ['name', string()],
    vehicleType: ['vehicle_type', optional(vehicleTypeSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
