/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DirectionsTrafficSpeedEntry {
  /** The current traffic/speed conditions on this portion of a path. */
  speedCategory: string;
  /** The offset along the path (in meters) up to which this speed category is valid. */
  offsetMeters: number;
  additionalProperties?: Record<string, unknown>;
}

export const directionsTrafficSpeedEntrySchema: Schema<DirectionsTrafficSpeedEntry> = typedExpandoObject(
  {
    speedCategory: ['speed_category', string()],
    offsetMeters: ['offset_meters', number()],
  },
  'additionalProperties',
  optional(unknown())
);
