/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DistanceMatrixStatus
 */
export enum DistanceMatrixStatus {
  Ok = 'OK',
  InvalidRequest = 'INVALID_REQUEST',
  MaxElementsExceeded = 'MAX_ELEMENTS_EXCEEDED',
  MaxDimensionsExceeded = 'MAX_DIMENSIONS_EXCEEDED',
  OverDailyLimit = 'OVER_DAILY_LIMIT',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for DistanceMatrixStatus
 */
export const distanceMatrixStatusSchema: Schema<DistanceMatrixStatus> = stringEnum(
  DistanceMatrixStatus
);
