/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DistanceMatrixElementStatus
 */
export enum DistanceMatrixElementStatus {
  Ok = 'OK',
  NotFound = 'NOT_FOUND',
  ZeroResults = 'ZERO_RESULTS',
  MaxRouteLengthExceeded = 'MAX_ROUTE_LENGTH_EXCEEDED',
}

/**
 * Schema for DistanceMatrixElementStatus
 */
export const distanceMatrixElementStatusSchema: Schema<DistanceMatrixElementStatus> = stringEnum(
  DistanceMatrixElementStatus
);
