/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DistanceMatrixRow,
  distanceMatrixRowSchema,
} from './distanceMatrixRow.js';
import {
  DistanceMatrixStatus,
  distanceMatrixStatusSchema,
} from './distanceMatrixStatus.js';

export interface DistanceMatrixResponse {
  /** An array of addresses as returned by the API from your original request. These are formatted by the geocoder and localized according to the language parameter passed with the request. This content is meant to be read as-is. Do not programatically parse the formatted addresses. */
  originAddresses: string[];
  /** An array of addresses as returned by the API from your original request. As with `origin_addresses`, these are localized if appropriate. This content is meant to be read as-is. Do not programatically parse the formatted addresses. */
  destinationAddresses: string[];
  /** An array of elements, which in turn each contain a `status`, `duration`, and `distance` element. */
  rows: DistanceMatrixRow[];
  status: DistanceMatrixStatus;
  /** A string containing the human-readable text of any errors encountered while the request was being processed. */
  errorMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export const distanceMatrixResponseSchema: Schema<DistanceMatrixResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        originAddresses: ['origin_addresses', array(string())],
        destinationAddresses: ['destination_addresses', array(string())],
        rows: ['rows', array(distanceMatrixRowSchema)],
        status: ['status', distanceMatrixStatusSchema],
        errorMessage: ['error_message', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
