/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Distance, distanceSchema } from './distance.js';
import {
  DistanceMatrixElementStatus,
  distanceMatrixElementStatusSchema,
} from './distanceMatrixElementStatus.js';
import { Duration, durationSchema } from './duration.js';
import {
  DurationInTraffic,
  durationInTrafficSchema,
} from './durationInTraffic.js';
import { Fare1, fare1Schema } from './fare1.js';

export interface DistanceMatrixElement {
  fare?: Fare1;
  distance?: Distance;
  durationInTraffic?: DurationInTraffic;
  duration?: Duration;
  status: DistanceMatrixElementStatus;
  additionalProperties?: Record<string, unknown>;
}

export const distanceMatrixElementSchema: Schema<DistanceMatrixElement> = lazy(
  () =>
    typedExpandoObject(
      {
        fare: ['fare', optional(fare1Schema)],
        distance: ['distance', optional(distanceSchema)],
        durationInTraffic: [
          'duration_in_traffic',
          optional(durationInTrafficSchema),
        ],
        duration: ['duration', optional(durationSchema)],
        status: ['status', distanceMatrixElementStatusSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
