/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Duration {
  /** String value. */
  text: string;
  /** Numeric value. */
  value: number;
  additionalProperties?: Record<string, unknown>;
}

export const durationSchema: Schema<Duration> = typedExpandoObject(
  { text: ['text', string()], value: ['value', number()] },
  'additionalProperties',
  optional(unknown())
);
