/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EditorialSummary {
  /** A medium-length textual summary of the place. */
  overview?: string;
  /** The language of the previous fields. May not always be present. */
  language?: string;
  additionalProperties?: Record<string, unknown>;
}

export const editorialSummarySchema: Schema<EditorialSummary> = typedExpandoObject(
  {
    overview: ['overview', optional(string())],
    language: ['language', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
