/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';

export interface ElevationResult {
  /** The elevation of the location in meters. */
  elevation: number;
  /** The value indicating the maximum distance between data points from which the elevation was interpolated, in meters. This property will be missing if the resolution is not known. Note that elevation data becomes more coarse (larger resolution values) when multiple points are passed. To obtain the most accurate elevation value for a point, it should be queried independently. */
  resolution?: number;
  location: Location;
  additionalProperties?: Record<string, unknown>;
}

export const elevationResultSchema: Schema<ElevationResult> = lazy(() =>
  typedExpandoObject(
    {
      elevation: ['elevation', number()],
      resolution: ['resolution', optional(number())],
      location: ['location', locationSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
