/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ElevationStatus
 */
export enum ElevationStatus {
  Ok = 'OK',
  DataNotAvailable = 'DATA_NOT_AVAILABLE',
  InvalidRequest = 'INVALID_REQUEST',
  OverDailyLimit = 'OVER_DAILY_LIMIT',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for ElevationStatus
 */
export const elevationStatusSchema: Schema<ElevationStatus> = stringEnum(
  ElevationStatus
);
