/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorObject, errorObjectSchema } from './errorObject.js';

/** In the case of an error, a standard format error response body will be returned and the HTTP status code will be set to an error status. The response contains an object with a single error object. */
export interface ErrorResponse {
  error: ErrorObject;
  additionalProperties?: Record<string, unknown>;
}

export const errorResponseSchema: Schema<ErrorResponse> = lazy(() =>
  typedExpandoObject(
    { error: ['error', errorObjectSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
