/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorDetail, errorDetailSchema } from './errorDetail.js';

export interface ErrorObject {
  /** This is the same as the HTTP status of the response. */
  code: number;
  /** A short description of the error. */
  message: string;
  /** A list of errors which occurred. Each error contains an identifier for the type of error and a short description. */
  errors: ErrorDetail[];
  /** A status code that indicates the error type. */
  status?: string;
  /** Additional details about the error. */
  details?: ErrorDetail[];
  additionalProperties?: Record<string, unknown>;
}

export const errorObjectSchema: Schema<ErrorObject> = lazy(() =>
  typedExpandoObject(
    {
      code: ['code', number()],
      message: ['message', string()],
      errors: ['errors', array(errorDetailSchema)],
      status: ['status', optional(string())],
      details: ['details', optional(array(errorDetailSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
