/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FieldViolation, fieldViolationSchema } from './fieldViolation.js';

export interface ErrorDetail {
  /** The type of error. */
  mType?: string;
  /** A short description of the error. */
  message?: string;
  /** A reason for the error. */
  reason?: string;
  /** The domain in which the error occurred. */
  domain?: string;
  /** Additional metadata about the error. */
  metadata?: unknown;
  /** A list of field violations. */
  fieldViolations?: FieldViolation[];
  additionalProperties?: Record<string, unknown>;
}

export const errorDetailSchema: Schema<ErrorDetail> = lazy(() =>
  typedExpandoObject(
    {
      mType: ['@type', optional(string())],
      message: ['message', optional(string())],
      reason: ['reason', optional(string())],
      domain: ['domain', optional(string())],
      metadata: ['metadata', optional(unknown())],
      fieldViolations: [
        'fieldViolations',
        optional(array(fieldViolationSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
