/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Fare1 {
  /** An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency that the amount is expressed in. */
  currency: string;
  /** The total fare amount, in the currency specified. */
  value: number;
  /** The total fare amount, formatted in the requested language. */
  text: string;
  additionalProperties?: Record<string, unknown>;
}

export const fare1Schema: Schema<Fare1> = typedExpandoObject(
  {
    currency: ['currency', string()],
    value: ['value', number()],
    text: ['text', string()],
  },
  'additionalProperties',
  optional(unknown())
);
