/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FieldViolation {
  /** The name of the invalid field. */
  field: string;
  /** A short description of the error. */
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const fieldViolationSchema: Schema<FieldViolation> = typedExpandoObject(
  { field: ['field', string()], description: ['description', string()] },
  'additionalProperties',
  optional(unknown())
);
