/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for GeocoderStatus
 */
export enum GeocoderStatus {
  Ok = 'OK',
  ZeroResults = 'ZERO_RESULTS',
}

/**
 * Schema for GeocoderStatus
 */
export const geocoderStatusSchema: Schema<GeocoderStatus> = stringEnum(
  GeocoderStatus
);
