/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Bounds1, bounds1Schema } from './bounds1.js';
import { Location, locationSchema } from './location.js';
import { Viewport, viewportSchema } from './viewport.js';

/** An object describing the location. */
export interface GeocodingGeometry {
  location: Location;
  bounds?: Bounds1;
  viewport: Viewport;
  additionalProperties?: Record<string, unknown>;
}

export const geocodingGeometrySchema: Schema<GeocodingGeometry> = lazy(() =>
  typedExpandoObject(
    {
      location: ['location', locationSchema],
      bounds: ['bounds', optional(bounds1Schema)],
      viewport: ['viewport', viewportSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
