/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AddressComponent,
  addressComponentSchema,
} from './addressComponent.js';
import { Geometry1, geometry1Schema } from './geometry1.js';
import { PlusCode1, plusCode1Schema } from './plusCode1.js';

export interface GeocodingResult {
  /** An array containing the separate components applicable to this address. */
  addressComponents: AddressComponent[];
  /** The human-readable address of this location. */
  formattedAddress: string;
  geometry: Geometry1;
  /** A unique identifier that can be used with other Google APIs. For example, you can use the `place_id` in a Places API request to get details of a local business, such as phone number, opening hours, user reviews, and more. See the [place ID overview](https://developers.google.com/places/place-id). */
  placeId: string;
  plusCode?: PlusCode1;
  /** The `types[]` array indicates the type of the returned result. This array contains a set of zero or more tags identifying the type of feature returned in the result. For example, a geocode of "Chicago" returns "locality" which indicates that "Chicago" is a city, and also returns "political" which indicates it is a political entity. */
  types: string[];
  /** An array denoting all the localities contained in a postal code. This is only present when the result is a postal code that contains multiple localities. */
  postcodeLocalities?: string[];
  /**
   * Indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.
   * Partial matches most often occur for street addresses that do not exist within the locality you pass in the request. Partial matches may also be returned when a request matches two or more locations in the same locality.
   */
  partialMatch?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const geocodingResultSchema: Schema<GeocodingResult> = lazy(() =>
  typedExpandoObject(
    {
      addressComponents: ['address_components', array(addressComponentSchema)],
      formattedAddress: ['formatted_address', string()],
      geometry: ['geometry', geometry1Schema],
      placeId: ['place_id', string()],
      plusCode: ['plus_code', optional(plusCode1Schema)],
      types: ['types', array(string())],
      postcodeLocalities: ['postcode_localities', optional(array(string()))],
      partialMatch: ['partial_match', optional(boolean())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
