/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { GeocodingResult, geocodingResultSchema } from './geocodingResult.js';
import { GeocodingStatus, geocodingStatusSchema } from './geocodingStatus.js';
import { PlusCode1, plusCode1Schema } from './plusCode1.js';

export interface GeocodingResponse {
  plusCode?: PlusCode1;
  results: GeocodingResult[];
  status: GeocodingStatus;
  /** A short description of the error. */
  errorMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export const geocodingResponseSchema: Schema<GeocodingResponse> = lazy(() =>
  typedExpandoObject(
    {
      plusCode: ['plus_code', optional(plusCode1Schema)],
      results: ['results', array(geocodingResultSchema)],
      status: ['status', geocodingStatusSchema],
      errorMessage: ['error_message', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
