/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';

export interface GeolocationV1GeolocateResponse {
  location: Location;
  /** The accuracy of the estimated location, in meters. This represents the radius of a circle around the given `location`. If your Geolocation response shows a very high value in the `accuracy` field, the service may be geolocating based on the  request IP, instead of WiFi points or cell towers. This can happen if no cell towers or access points are valid or recognized. To confirm that this is the issue, set `considerIp` to `false` in your request. If the response is a `404`, you've confirmed that your `wifiAccessPoints` and `cellTowers` objects could not be geolocated. */
  accuracy: number;
  additionalProperties?: Record<string, unknown>;
}

export const geolocationV1GeolocateResponseSchema: Schema<GeolocationV1GeolocateResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        location: ['location', locationSchema],
        accuracy: ['accuracy', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
