/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CellTower, cellTowerSchema } from './cellTower.js';
import { WiFiAccessPoint, wiFiAccessPointSchema } from './wiFiAccessPoint.js';

/** The request body must be formatted as JSON. The following fields are supported, and all fields are optional. */
export interface GeolocationRequest {
  /** The cell tower's Mobile Country Code (MCC). */
  homeMobileCountryCode?: number;
  /** The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID). */
  homeMobileNetworkCode?: number;
  /** The mobile radio type. Supported values are lte, gsm, cdma, and wcdma. While this field is optional, it should be included if a value is available, for more accurate results. */
  radioType?: string;
  /** The carrier name. */
  carrier?: string;
  /** Specifies whether to fall back to IP geolocation if wifi and cell tower signals are not available. Defaults to true. Set considerIp to false to disable fall back. */
  considerIp?: string;
  /** The request body's cellTowers array contains zero or more cell tower objects. */
  cellTowers?: CellTower[];
  /** An array of two or more WiFi access point objects. */
  wifiAccessPoints?: WiFiAccessPoint[];
  additionalProperties?: Record<string, unknown>;
}

export const geolocationRequestSchema: Schema<GeolocationRequest> = lazy(() =>
  typedExpandoObject(
    {
      homeMobileCountryCode: ['homeMobileCountryCode', optional(number())],
      homeMobileNetworkCode: ['homeMobileNetworkCode', optional(number())],
      radioType: ['radioType', optional(string())],
      carrier: ['carrier', optional(string())],
      considerIp: ['considerIp', optional(string())],
      cellTowers: ['cellTowers', optional(array(cellTowerSchema))],
      wifiAccessPoints: [
        'wifiAccessPoints',
        optional(array(wiFiAccessPointSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
