/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';
import { Viewport, viewportSchema } from './viewport.js';

export interface Geometry2 {
  location: Location;
  viewport: Viewport;
  additionalProperties?: Record<string, unknown>;
}

export const geometry2Schema: Schema<Geometry2> = lazy(() =>
  typedExpandoObject(
    {
      location: ['location', locationSchema],
      viewport: ['viewport', viewportSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
