/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Inputtype1
 */
export enum Inputtype1 {
  Textquery = 'textquery',
  Phonenumber = 'phonenumber',
}

/**
 * Schema for Inputtype1
 */
export const inputtype1Schema: Schema<Inputtype1> = stringEnum(Inputtype1);
