/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Inputtype
 */
export enum Inputtype {
  Textquery = 'textquery',
  Phonenumber = 'phonenumber',
}

/**
 * Schema for Inputtype
 */
export const inputtypeSchema: Schema<Inputtype> = stringEnum(Inputtype);
