/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Language1
 */
export enum Language1 {
  Ar = 'ar',
  Bg = 'bg',
  Bn = 'bn',
  Ca = 'ca',
  Cs = 'cs',
  Da = 'da',
  De = 'de',
  El = 'el',
  En = 'en',
  EnAu = 'en-AU',
  EnGb = 'en-GB',
  Es = 'es',
  Eu = 'eu',
  Fa = 'fa',
  Fi = 'fi',
  Fil = 'fil',
  Fr = 'fr',
  Gl = 'gl',
  Gu = 'gu',
  Hi = 'hi',
  Hr = 'hr',
  Hu = 'hu',
  Id = 'id',
  It = 'it',
  Iw = 'iw',
  Ja = 'ja',
  Kn = 'kn',
  Ko = 'ko',
  Lt = 'lt',
  Lv = 'lv',
  Ml = 'ml',
  Mr = 'mr',
  Nl = 'nl',
  No = 'no',
  Pl = 'pl',
  Pt = 'pt',
  PtBr = 'pt-BR',
  PtPt = 'pt-PT',
  Ro = 'ro',
  Ru = 'ru',
  Sk = 'sk',
  Sl = 'sl',
  Sr = 'sr',
  Sv = 'sv',
  Ta = 'ta',
  Te = 'te',
  Th = 'th',
  Tl = 'tl',
  Tr = 'tr',
  Uk = 'uk',
  Vi = 'vi',
  ZhCn = 'zh-CN',
  ZhTw = 'zh-TW',
}

/**
 * Schema for Language1
 */
export const language1Schema: Schema<Language1> = stringEnum(Language1);
