/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object describing a specific location with Latitude and Longitude in decimal degrees. */
export interface LatitudeLongitudeLiteral {
  /** Latitude in decimal degrees */
  latitude: number;
  /** Longitude in decimal degrees */
  longitude: number;
  additionalProperties?: Record<string, unknown>;
}

export const latitudeLongitudeLiteralSchema: Schema<LatitudeLongitudeLiteral> = typedExpandoObject(
  { latitude: ['latitude', number()], longitude: ['longitude', number()] },
  'additionalProperties',
  optional(unknown())
);
