/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object describing a specific location with Latitude and Longitude in decimal degrees. */
export interface LatLngLiteral {
  /** Latitude in decimal degrees */
  lat: number;
  /** Longitude in decimal degrees */
  lng: number;
  additionalProperties?: Record<string, unknown>;
}

export const latLngLiteralSchema: Schema<LatLngLiteral> = typedExpandoObject(
  { lat: ['lat', number()], lng: ['lng', number()] },
  'additionalProperties',
  optional(unknown())
);
