/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Location {
  /** Latitude in decimal degrees */
  lat: number;
  /** Longitude in decimal degrees */
  lng: number;
  additionalProperties?: Record<string, unknown>;
}

export const locationSchema: Schema<Location> = typedExpandoObject(
  { lat: ['lat', number()], lng: ['lng', number()] },
  'additionalProperties',
  optional(unknown())
);
