/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Location6 {
  /** Latitude in decimal degrees */
  latitude: number;
  /** Longitude in decimal degrees */
  longitude: number;
  additionalProperties?: Record<string, unknown>;
}

export const location6Schema: Schema<Location6> = typedExpandoObject(
  { latitude: ['latitude', number()], longitude: ['longitude', number()] },
  'additionalProperties',
  optional(unknown())
);
