/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LocationType
 */
export enum LocationType {
  Approximate = 'APPROXIMATE',
  GeometricCenter = 'GEOMETRIC_CENTER',
  RangeInterpolated = 'RANGE_INTERPOLATED',
  Rooftop = 'ROOFTOP',
}

/**
 * Schema for LocationType
 */
export const locationTypeSchema: Schema<LocationType> = stringEnum(
  LocationType
);
