/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Maneuver
 */
export enum Maneuver {
  Turnslightleft = 'turn-slight-left',
  Turnsharpleft = 'turn-sharp-left',
  Turnleft = 'turn-left',
  Turnslightright = 'turn-slight-right',
  Turnsharpright = 'turn-sharp-right',
  Keepright = 'keep-right',
  Keepleft = 'keep-left',
  Uturnleft = 'uturn-left',
  Uturnright = 'uturn-right',
  Turnright = 'turn-right',
  Straight = 'straight',
  Rampleft = 'ramp-left',
  Rampright = 'ramp-right',
  Merge = 'merge',
  Forkleft = 'fork-left',
  Forkright = 'fork-right',
  Ferry = 'ferry',
  Ferrytrain = 'ferry-train',
  Roundaboutleft = 'roundabout-left',
  Roundaboutright = 'roundabout-right',
}

/**
 * Schema for Maneuver
 */
export const maneuverSchema: Schema<Maneuver> = stringEnum(Maneuver);
