/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ElevationStatus, elevationStatusSchema } from './elevationStatus.js';
import { Result, resultSchema } from './result.js';

export interface MapsApiElevationJsonResponse {
  /** When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. */
  errorMessage?: string;
  status: ElevationStatus;
  results: Result[];
  additionalProperties?: Record<string, unknown>;
}

export const mapsApiElevationJsonResponseSchema: Schema<MapsApiElevationJsonResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        errorMessage: ['error_message', optional(string())],
        status: ['status', elevationStatusSchema],
        results: ['results', array(resultSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
