/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Minprice
 */
export enum Minprice {
  Enum0 = '0',
  Enum1 = '1',
  Enum2 = '2',
  Enum3 = '3',
  Enum4 = '4',
}

/**
 * Schema for Minprice
 */
export const minpriceSchema: Schema<Minprice> = stringEnum(Minprice);
