/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Mode1
 */
export enum Mode1 {
  Driving = 'driving',
  Bicycling = 'bicycling',
  Transit = 'transit',
  Walking = 'walking',
}

/**
 * Schema for Mode1
 */
export const mode1Schema: Schema<Mode1> = stringEnum(Mode1);
