/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  NearestRoadsError,
  nearestRoadsErrorSchema,
} from './nearestRoadsError.js';

export interface NearestRoadsErrorResponse {
  error?: NearestRoadsError;
  additionalProperties?: Record<string, unknown>;
}

export const nearestRoadsErrorResponseSchema: Schema<NearestRoadsErrorResponse> = lazy(
  () =>
    typedExpandoObject(
      { error: ['error', optional(nearestRoadsErrorSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
