/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { SnappedPoint, snappedPointSchema } from './snappedPoint.js';

export interface NearestRoadsResponse {
  /** An array of snapped points. Sometimes containing several snapped points for the same point with differing placeId or location. */
  snappedPoints?: SnappedPoint[];
  additionalProperties?: Record<string, unknown>;
}

export const nearestRoadsResponseSchema: Schema<NearestRoadsResponse> = lazy(
  () =>
    typedExpandoObject(
      { snappedPoints: ['snappedPoints', optional(array(snappedPointSchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
