/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NearestRoadsError {
  /** This is the same as the HTTP status of the response. */
  code: number;
  /** A short description of the error. */
  message: string;
  /** An error such as `INVALID_ARGUMENT`. */
  status: string;
  additionalProperties?: Record<string, unknown>;
}

export const nearestRoadsErrorSchema: Schema<NearestRoadsError> = typedExpandoObject(
  {
    code: ['code', number()],
    message: ['message', string()],
    status: ['status', string()],
  },
  'additionalProperties',
  optional(unknown())
);
