/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlaceOpeningHoursPeriod,
  placeOpeningHoursPeriodSchema,
} from './placeOpeningHoursPeriod.js';
import { PlaceSpecialDay, placeSpecialDaySchema } from './placeSpecialDay.js';

export interface OpeningHours {
  /** A boolean value indicating if the place is open at the current time. */
  openNow?: boolean;
  /** An array of opening periods covering seven days, starting from Sunday, in chronological order. */
  periods?: PlaceOpeningHoursPeriod[];
  /** An array of up to seven entries corresponding to the next seven days. */
  specialDays?: PlaceSpecialDay[];
  /** A type string used to identify the type of secondary hours (for example, `DRIVE_THROUGH`, `HAPPY_HOUR`, `DELIVERY`, `TAKEOUT`, `KITCHEN`, `BREAKFAST`, `LUNCH`, `DINNER`, `BRUNCH`, `PICKUP`, `SENIOR_HOURS`). Set for `secondary_opening_hours` only. */
  type?: string;
  /** An array of strings describing in human-readable text the hours of the place. */
  weekdayText?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const openingHoursSchema: Schema<OpeningHours> = lazy(() =>
  typedExpandoObject(
    {
      openNow: ['open_now', optional(boolean())],
      periods: ['periods', optional(array(placeOpeningHoursPeriodSchema))],
      specialDays: ['special_days', optional(array(placeSpecialDaySchema))],
      type: ['type', optional(string())],
      weekdayText: ['weekday_text', optional(array(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
