/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OverviewPolyline {
  /** A single string representation of the polyline. */
  points: string;
  additionalProperties?: Record<string, unknown>;
}

export const overviewPolylineSchema: Schema<OverviewPolyline> = typedExpandoObject(
  { points: ['points', string()] },
  'additionalProperties',
  optional(unknown())
);
