/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlaceAutocompleteMatchedSubstring,
  placeAutocompleteMatchedSubstringSchema,
} from './placeAutocompleteMatchedSubstring.js';
import {
  PlaceAutocompleteStructuredFormat,
  placeAutocompleteStructuredFormatSchema,
} from './placeAutocompleteStructuredFormat.js';
import {
  PlaceAutocompleteTerm,
  placeAutocompleteTermSchema,
} from './placeAutocompleteTerm.js';

export interface PlaceAutocompletePrediction {
  /** Contains the human-readable name for the returned result. For `establishment` results, this is usually the business name. This content is meant to be read as-is. Do not programmatically parse the formatted address. */
  description: string;
  /** A list of substrings that describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
  matchedSubstrings: PlaceAutocompleteMatchedSubstring[];
  /** A textual identifier that uniquely identifies a place. To retrieve information about the place, pass this identifier in the placeId field of a Places API request. For more information about place IDs, see the [Place IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview. */
  placeId?: string;
  /** See place_id. */
  reference?: string;
  structuredFormatting: PlaceAutocompleteStructuredFormat;
  /** Contains an array of terms identifying each section of the returned description (a section of the description is generally terminated with a comma). Each entry in the array has a `value` field, containing the text of the term, and an `offset` field, defining the start position of this term in the description, measured in Unicode characters. */
  terms: PlaceAutocompleteTerm[];
  /** Contains an array of types that apply to this place. For example: `[ "political", "locality" ]` or `[ "establishment", "geocode", "beauty_salon" ]`. The array can contain multiple values. Learn more about [Place types](https://developers.google.com/maps/documentation/places/web-service/supported_types). */
  types?: string[];
  /** The straight-line distance in meters from the origin. This field is only returned for requests made with an `origin`. */
  distanceMeters?: number;
  additionalProperties?: Record<string, unknown>;
}

export const placeAutocompletePredictionSchema: Schema<PlaceAutocompletePrediction> = lazy(
  () =>
    typedExpandoObject(
      {
        description: ['description', string()],
        matchedSubstrings: [
          'matched_substrings',
          array(placeAutocompleteMatchedSubstringSchema),
        ],
        placeId: ['place_id', optional(string())],
        reference: ['reference', optional(string())],
        structuredFormatting: [
          'structured_formatting',
          placeAutocompleteStructuredFormatSchema,
        ],
        terms: ['terms', array(placeAutocompleteTermSchema)],
        types: ['types', optional(array(string()))],
        distanceMeters: ['distance_meters', optional(number())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
