/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/**
 * A photo of a Place. The photo can be accesed via the [Place Photo](https://developers.google.com/places/web-service/photos) API using an url in the following pattern:
 * ```
 * https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=photo_reference&key=YOUR_API_KEY
 * ```
 * See [Place Photos](https://developers.google.com/places/web-service/photos) for more information.
 */
export interface PlacePhoto {
  /** The height of the photo. */
  height: number;
  /** The width of the photo. */
  width: number;
  /** The HTML attributions for the photo. */
  htmlAttributions: string[];
  /** A string used to identify the photo when you perform a Photo request. */
  photoReference: string;
  additionalProperties?: Record<string, unknown>;
}

export const placePhotoSchema: Schema<PlacePhoto> = typedExpandoObject(
  {
    height: ['height', number()],
    width: ['width', number()],
    htmlAttributions: ['html_attributions', array(string())],
    photoReference: ['photo_reference', string()],
  },
  'additionalProperties',
  optional(unknown())
);
