/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlacesDetailsStatus,
  placesDetailsStatusSchema,
} from './placesDetailsStatus.js';
import { Result2, result2Schema } from './result2.js';

export interface PlacesDetailsResponse {
  /** May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution). */
  htmlAttributions: string[];
  result: Result2;
  status: PlacesDetailsStatus;
  /** When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. */
  infoMessages?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const placesDetailsResponseSchema: Schema<PlacesDetailsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        htmlAttributions: ['html_attributions', array(string())],
        result: ['result', result2Schema],
        status: ['status', placesDetailsStatusSchema],
        infoMessages: ['info_messages', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
