/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PlaceSpecialDay {
  /** A date expressed in RFC3339 format in the local timezone for the place, for example 2010-12-31. */
  date?: string;
  /** True if there are exceptional hours for this day. If `true`, this means that there is at least one exception for this day. Exceptions cause different values to occur in the subfields of `current_opening_hours` and `secondary_opening_hours` such as `periods`, `weekday_text`, `open_now`. The exceptions apply to the hours, and the hours are used to generate the other fields. */
  exceptionalHours?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const placeSpecialDaySchema: Schema<PlaceSpecialDay> = typedExpandoObject(
  {
    date: ['date', optional(string())],
    exceptionalHours: ['exceptional_hours', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
