/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlaceAutocompletePrediction,
  placeAutocompletePredictionSchema,
} from './placeAutocompletePrediction.js';
import {
  PlacesAutocompleteStatus,
  placesAutocompleteStatusSchema,
} from './placesAutocompleteStatus.js';

export interface PlacesAutocompleteResponse {
  /** Contains an array of predictions. */
  predictions: PlaceAutocompletePrediction[];
  status: PlacesAutocompleteStatus;
  /** When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. */
  errorMessage?: string;
  /** When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. */
  infoMessages?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const placesAutocompleteResponseSchema: Schema<PlacesAutocompleteResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        predictions: ['predictions', array(placeAutocompletePredictionSchema)],
        status: ['status', placesAutocompleteStatusSchema],
        errorMessage: ['error_message', optional(string())],
        infoMessages: ['info_messages', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
