/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlaceAutocompleteMatchedSubstring,
  placeAutocompleteMatchedSubstringSchema,
} from './placeAutocompleteMatchedSubstring.js';

export interface PlaceAutocompleteStructuredFormat {
  /** Contains the main text of a prediction, usually the name of the place. */
  mainText: string;
  /** Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
  mainTextMatchedSubstrings: PlaceAutocompleteMatchedSubstring[];
  /** Contains the secondary text of a prediction, usually the location of the place. */
  secondaryText?: string;
  /** Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
  secondaryTextMatchedSubstrings?: PlaceAutocompleteMatchedSubstring[];
  additionalProperties?: Record<string, unknown>;
}

export const placeAutocompleteStructuredFormatSchema: Schema<PlaceAutocompleteStructuredFormat> = lazy(
  () =>
    typedExpandoObject(
      {
        mainText: ['main_text', string()],
        mainTextMatchedSubstrings: [
          'main_text_matched_substrings',
          array(placeAutocompleteMatchedSubstringSchema),
        ],
        secondaryText: ['secondary_text', optional(string())],
        secondaryTextMatchedSubstrings: [
          'secondary_text_matched_substrings',
          optional(array(placeAutocompleteMatchedSubstringSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
