/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Place, placeSchema } from './place.js';
import {
  PlacesSearchStatus,
  placesSearchStatusSchema,
} from './placesSearchStatus.js';

export interface PlacesFindPlaceFromTextResponse {
  /**
   * Contains an array of Place candidates.
   * <div class="caution">Place Search requests return a subset of the fields that are returned by Place Details requests. If the field you want is not returned by Place Search, you can use Place Search to get a place_id, then use that Place ID to make a Place Details request.</div>
   */
  candidates: Place[];
  status: PlacesSearchStatus;
  /** When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. */
  errorMessage?: string;
  /** When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. */
  infoMessages?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const placesFindPlaceFromTextResponseSchema: Schema<PlacesFindPlaceFromTextResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        candidates: ['candidates', array(placeSchema)],
        status: ['status', placesSearchStatusSchema],
        errorMessage: ['error_message', optional(string())],
        infoMessages: ['info_messages', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
