/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PlaceAutocompleteMatchedSubstring {
  /** Length of the matched substring in the prediction result text. */
  length: number;
  /** Start location of the matched substring in the prediction result text. */
  offset: number;
  additionalProperties?: Record<string, unknown>;
}

export const placeAutocompleteMatchedSubstringSchema: Schema<PlaceAutocompleteMatchedSubstring> = typedExpandoObject(
  { length: ['length', number()], offset: ['offset', number()] },
  'additionalProperties',
  optional(unknown())
);
