/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PlaceAutocompleteTerm {
  /** The text of the term. */
  value: string;
  /** Defines the start position of this term in the description, measured in Unicode characters */
  offset: number;
  additionalProperties?: Record<string, unknown>;
}

export const placeAutocompleteTermSchema: Schema<PlaceAutocompleteTerm> = typedExpandoObject(
  { value: ['value', string()], offset: ['offset', number()] },
  'additionalProperties',
  optional(unknown())
);
