/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PlacesAutocompleteStatus
 */
export enum PlacesAutocompleteStatus {
  Ok = 'OK',
  ZeroResults = 'ZERO_RESULTS',
  InvalidRequest = 'INVALID_REQUEST',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for PlacesAutocompleteStatus
 */
export const placesAutocompleteStatusSchema: Schema<PlacesAutocompleteStatus> = stringEnum(
  PlacesAutocompleteStatus
);
