/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PlaceOpeningHoursPeriodDetail,
  placeOpeningHoursPeriodDetailSchema,
} from './placeOpeningHoursPeriodDetail.js';

export interface PlaceOpeningHoursPeriod {
  open: PlaceOpeningHoursPeriodDetail;
  close?: PlaceOpeningHoursPeriodDetail;
  additionalProperties?: Record<string, unknown>;
}

export const placeOpeningHoursPeriodSchema: Schema<PlaceOpeningHoursPeriod> = lazy(
  () =>
    typedExpandoObject(
      {
        open: ['open', placeOpeningHoursPeriodDetailSchema],
        close: ['close', optional(placeOpeningHoursPeriodDetailSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
