/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PlacesDetailsStatus
 */
export enum PlacesDetailsStatus {
  Ok = 'OK',
  ZeroResults = 'ZERO_RESULTS',
  InvalidRequest = 'INVALID_REQUEST',
  NotFound = 'NOT_FOUND',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for PlacesDetailsStatus
 */
export const placesDetailsStatusSchema: Schema<PlacesDetailsStatus> = stringEnum(
  PlacesDetailsStatus
);
