/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PlusCode1 {
  /** The `compound_code` is a 6 character or longer local code with an explicit location (`CWC8+R9, Mountain View, CA, USA`). Some APIs may return an empty string if the `compound_code` is not available. */
  compoundCode?: string;
  /** The `global_code` is a 4 character area code and 6 character or longer local code (`849VCWC8+R9`). */
  globalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const plusCode1Schema: Schema<PlusCode1> = typedExpandoObject(
  {
    compoundCode: ['compound_code', optional(string())],
    globalCode: ['global_code', string()],
  },
  'additionalProperties',
  optional(unknown())
);
