/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An encoded location reference, derived from latitude and longitude coordinates, that represents an area, 1/8000th of a degree by 1/8000th of a degree (about 14m x 14m at the equator) or smaller. Plus codes can be used as a replacement for street addresses in places where they do not exist (where buildings are not numbered or streets are not named). */
export interface PlusCode {
  /** The `compound_code` is a 6 character or longer local code with an explicit location (`CWC8+R9, Mountain View, CA, USA`). Some APIs may return an empty string if the `compound_code` is not available. */
  compoundCode?: string;
  /** The `global_code` is a 4 character area code and 6 character or longer local code (`849VCWC8+R9`). */
  globalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const plusCodeSchema: Schema<PlusCode> = typedExpandoObject(
  {
    compoundCode: ['compound_code', optional(string())],
    globalCode: ['global_code', string()],
  },
  'additionalProperties',
  optional(unknown())
);
