/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Polyline {
  /** A single string representation of the polyline. */
  points: string;
  additionalProperties?: Record<string, unknown>;
}

export const polylineSchema: Schema<Polyline> = typedExpandoObject(
  { points: ['points', string()] },
  'additionalProperties',
  optional(unknown())
);
