/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Rankby
 */
export enum Rankby {
  Prominence = 'prominence',
  Distance = 'distance',
}

/**
 * Schema for Rankby
 */
export const rankbySchema: Schema<Rankby> = stringEnum(Rankby);
