/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Rankby1
 */
export enum Rankby1 {
  Prominence = 'prominence',
  Distance = 'distance',
}

/**
 * Schema for Rankby1
 */
export const rankby1Schema: Schema<Rankby1> = stringEnum(Rankby1);
