/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AddressComponent,
  addressComponentSchema,
} from './addressComponent.js';
import { BusinessStatus, businessStatusSchema } from './businessStatus.js';
import {
  CurrentOpeningHours,
  currentOpeningHoursSchema,
} from './currentOpeningHours.js';
import {
  EditorialSummary,
  editorialSummarySchema,
} from './editorialSummary.js';
import { Geometry2, geometry2Schema } from './geometry2.js';
import { OpeningHours, openingHoursSchema } from './openingHours.js';
import {
  PlaceOpeningHours,
  placeOpeningHoursSchema,
} from './placeOpeningHours.js';
import { PlacePhoto, placePhotoSchema } from './placePhoto.js';
import { PlaceReview, placeReviewSchema } from './placeReview.js';
import { PlusCode1, plusCode1Schema } from './plusCode1.js';

export interface Result2 {
  /** An array containing the separate components applicable to this address. */
  addressComponents?: AddressComponent[];
  /** A representation of the place's address in the [adr microformat](http://microformats.org/wiki/adr). */
  adrAddress?: string;
  businessStatus?: BusinessStatus;
  /** Specifies if the business supports curbside pickup. */
  curbsidePickup?: boolean;
  currentOpeningHours?: CurrentOpeningHours;
  /** Specifies if the business supports delivery. */
  delivery?: boolean;
  /** Specifies if the business supports indoor or outdoor seating options. */
  dineIn?: boolean;
  editorialSummary?: EditorialSummary;
  /**
   * A string containing the human-readable address of this place.
   * Often this address is equivalent to the postal address. Note that some countries, such as the United Kingdom, do not allow distribution of true postal addresses due to licensing restrictions.
   * The formatted address is logically composed of one or more address components. For example, the address "111 8th Avenue, New York, NY" consists of the following components: "111" (the street number), "8th Avenue" (the route), "New York" (the city) and "NY" (the US state).
   * Do not parse the formatted address programmatically. Instead you should use the individual address components, which the API response includes in addition to the formatted address field.
   */
  formattedAddress?: string;
  /** Contains the place's phone number in its [local format](http://en.wikipedia.org/wiki/Local_conventions_for_writing_telephone_numbers). */
  formattedPhoneNumber?: string;
  geometry?: Geometry2;
  /** Contains the URL of a suggested icon which may be displayed to the user when indicating this result on a map. */
  icon?: string;
  /** Contains the default HEX color code for the place's category. */
  iconBackgroundColor?: string;
  /** Contains the URL of a recommended icon, minus the `.svg` or `.png` file type extension. */
  iconMaskBaseUri?: string;
  /** Contains the place's phone number in international format. International format includes the country code, and is prefixed with the plus, +, sign. For example, the international_phone_number for Google's Sydney, Australia office is `+61 2 9374 4000`. */
  internationalPhoneNumber?: string;
  /** Contains the human-readable name for the returned result. For `establishment` results, this is usually the canonicalized business name. */
  name?: string;
  openingHours?: OpeningHours;
  /** Use `business_status` to get the operational status of businesses. */
  permanentlyClosed?: boolean;
  /** An array of photo objects, each containing a reference to an image. A request may return up to ten photos. More information about place photos and how you can use the images in your application can be found in the [Place Photos](https://developers.google.com/maps/documentation/places/web-service/photos) documentation. */
  photos?: PlacePhoto[];
  /** A textual identifier that uniquely identifies a place. To retrieve information about the place, pass this identifier in the `place_id` field of a Places API request. For more information about place IDs, see the [place ID overview](https://developers.google.com/maps/documentation/places/web-service/place-id). */
  placeId?: string;
  plusCode?: PlusCode1;
  /**
   * The price level of the place, on a scale of 0 to 4. The exact amount indicated by a specific value will vary from region to region. Price levels are interpreted as follows:
   * - 0 Free
   * - 1 Inexpensive
   * - 2 Moderate
   * - 3 Expensive
   * - 4 Very Expensive
   */
  priceLevel?: number;
  /** Contains the place's rating, from 1.0 to 5.0, based on aggregated user reviews. */
  rating?: number;
  reference?: string;
  /** Specifies if the place supports reservations. */
  reservable?: boolean;
  /**
   * A JSON array of up to five reviews. By default, the reviews are sorted in order of relevance. Use the `reviews_sort` request parameter to control sorting.
   * - For `most_relevant` (default), reviews are sorted by relevance; the service will bias the results to return reviews originally written in the preferred language.
   * - For `newest`, reviews are sorted in chronological order; the preferred language does not affect the sort order.
   * Google recommends indicating to users whether results are ordered by `most_relevant` or `newest`.
   */
  reviews?: PlaceReview[];
  /** Specifies if the place serves beer. */
  servesBeer?: boolean;
  /** Specifies if the place serves breakfast. */
  servesBreakfast?: boolean;
  /** Specifies if the place serves brunch. */
  servesBrunch?: boolean;
  /** Specifies if the place serves dinner. */
  servesDinner?: boolean;
  /** Specifies if the place serves lunch. */
  servesLunch?: boolean;
  /** Specifies if the place serves vegetarian food. */
  servesVegetarianFood?: boolean;
  /** Specifies if the place serves wine. */
  servesWine?: boolean;
  scope?: string;
  /** Contains an array of entries for the next seven days including information about secondary hours of a business. Secondary hours are different from a business's main hours. For example, a restaurant can specify drive through hours or delivery hours as its secondary hours. This field populates the `type` subfield, which draws from a predefined list of opening hours types (such as `DRIVE_THROUGH`, `PICKUP`, or `TAKEOUT`) based on the types of the place. This field includes the `special_days` subfield of all hours, set for dates that have exceptional hours. */
  secondaryOpeningHours?: PlaceOpeningHours[];
  /** Specifies if the business supports takeout. */
  takeout?: boolean;
  /** Contains an array of feature types describing the given result. See the list of [supported types](https://developers.google.com/maps/documentation/places/web-service/supported_types#table2). */
  types?: string[];
  /** Contains the URL of the official Google page for this place. This will be the Google-owned page that contains the best available information about the place. Applications must link to or embed this page on any screen that shows detailed results about the place to the user. */
  url?: string;
  /** The total number of reviews, with or without text, for this place. */
  userRatingsTotal?: number;
  /** Contains the number of minutes this place’s current timezone is offset from UTC. For example, for places in Sydney, Australia during daylight saving time this would be 660 (+11 hours from UTC), and for places in California outside of daylight saving time this would be -480 (-8 hours from UTC). */
  utcOffset?: number;
  /**
   * For establishment (`types:["establishment", ...])` results only, the `vicinity` field contains a simplified address for the place, including the street name, street number, and locality, but not the province/state, postal code, or country.
   * For all other results, the `vicinity` field contains the name of the narrowest political (`types:["political", ...]`) feature that is present in the address of the result.
   * This content is meant to be read as-is. Do not programmatically parse the formatted address.
   */
  vicinity?: string;
  /** The authoritative website for this place, such as a business' homepage. */
  website?: string;
  /** Specifies if the place has an entrance that is wheelchair-accessible. */
  wheelchairAccessibleEntrance?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const result2Schema: Schema<Result2> = lazy(() =>
  typedExpandoObject(
    {
      addressComponents: [
        'address_components',
        optional(array(addressComponentSchema)),
      ],
      adrAddress: ['adr_address', optional(string())],
      businessStatus: ['business_status', optional(businessStatusSchema)],
      curbsidePickup: ['curbside_pickup', optional(boolean())],
      currentOpeningHours: [
        'current_opening_hours',
        optional(currentOpeningHoursSchema),
      ],
      delivery: ['delivery', optional(boolean())],
      dineIn: ['dine_in', optional(boolean())],
      editorialSummary: ['editorial_summary', optional(editorialSummarySchema)],
      formattedAddress: ['formatted_address', optional(string())],
      formattedPhoneNumber: ['formatted_phone_number', optional(string())],
      geometry: ['geometry', optional(geometry2Schema)],
      icon: ['icon', optional(string())],
      iconBackgroundColor: ['icon_background_color', optional(string())],
      iconMaskBaseUri: ['icon_mask_base_uri', optional(string())],
      internationalPhoneNumber: [
        'international_phone_number',
        optional(string()),
      ],
      name: ['name', optional(string())],
      openingHours: ['opening_hours', optional(openingHoursSchema)],
      permanentlyClosed: ['permanently_closed', optional(boolean())],
      photos: ['photos', optional(array(placePhotoSchema))],
      placeId: ['place_id', optional(string())],
      plusCode: ['plus_code', optional(plusCode1Schema)],
      priceLevel: ['price_level', optional(number())],
      rating: ['rating', optional(number())],
      reference: ['reference', optional(string())],
      reservable: ['reservable', optional(boolean())],
      reviews: ['reviews', optional(array(placeReviewSchema))],
      servesBeer: ['serves_beer', optional(boolean())],
      servesBreakfast: ['serves_breakfast', optional(boolean())],
      servesBrunch: ['serves_brunch', optional(boolean())],
      servesDinner: ['serves_dinner', optional(boolean())],
      servesLunch: ['serves_lunch', optional(boolean())],
      servesVegetarianFood: ['serves_vegetarian_food', optional(boolean())],
      servesWine: ['serves_wine', optional(boolean())],
      scope: ['scope', optional(string())],
      secondaryOpeningHours: [
        'secondary_opening_hours',
        optional(array(placeOpeningHoursSchema)),
      ],
      takeout: ['takeout', optional(boolean())],
      types: ['types', optional(array(string()))],
      url: ['url', optional(string())],
      userRatingsTotal: ['user_ratings_total', optional(number())],
      utcOffset: ['utc_offset', optional(number())],
      vicinity: ['vicinity', optional(string())],
      website: ['website', optional(string())],
      wheelchairAccessibleEntrance: [
        'wheelchair_accessible_entrance',
        optional(boolean()),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
