/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ResultType
 */
export enum ResultType {
  AdministrativeAreaLevel1 = 'administrative_area_level_1',
  AdministrativeAreaLevel2 = 'administrative_area_level_2',
  AdministrativeAreaLevel3 = 'administrative_area_level_3',
  AdministrativeAreaLevel4 = 'administrative_area_level_4',
  AdministrativeAreaLevel5 = 'administrative_area_level_5',
  Airport = 'airport',
  ColloquialArea = 'colloquial_area',
  Country = 'country',
  Intersection = 'intersection',
  Locality = 'locality',
  NaturalFeature = 'natural_feature',
  Neighborhood = 'neighborhood',
  Park = 'park',
  PlusCode = 'plus_code',
  Political = 'political',
  PostalCode = 'postal_code',
  Premise = 'premise',
  Route = 'route',
  StreetAddress = 'street_address',
  Sublocality = 'sublocality',
  Subpremise = 'subpremise',
}

/**
 * Schema for ResultType
 */
export const resultTypeSchema: Schema<ResultType> = stringEnum(ResultType);
