/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { SnappedPoint, snappedPointSchema } from './snappedPoint.js';

export interface SnapToRoadsResponse {
  /** An array of snapped points. */
  snappedPoints?: SnappedPoint[];
  /** A string containing a user-visible warning. */
  warningMessage?: string;
  additionalProperties?: Record<string, unknown>;
}

export const snapToRoadsResponseSchema: Schema<SnapToRoadsResponse> = lazy(() =>
  typedExpandoObject(
    {
      snappedPoints: ['snappedPoints', optional(array(snappedPointSchema))],
      warningMessage: ['warningMessage', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
