/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Source1
 */
export enum Source1 {
  Default = 'default',
  Outdoor = 'outdoor',
}

/**
 * Schema for Source1
 */
export const source1Schema: Schema<Source1> = stringEnum(Source1);
