/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Source
 */
export enum Source {
  Default = 'default',
  Outdoor = 'outdoor',
}

/**
 * Schema for Source
 */
export const sourceSchema: Schema<Source> = stringEnum(Source);
