/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';
import {
  StreetViewStatus,
  streetViewStatusSchema,
} from './streetViewStatus.js';

export interface StreetViewResponse {
  /** Contains the copyright notices associated with this panorama. */
  copyright?: string;
  /** A string indicating year and month that the panorama was captured. */
  date?: string;
  location?: Location;
  /** A specific panorama ID. These are generally stable, though panoramas may change ID over time as imagery is refreshed. */
  panoId?: string;
  status: StreetViewStatus;
  additionalProperties?: Record<string, unknown>;
}

export const streetViewResponseSchema: Schema<StreetViewResponse> = lazy(() =>
  typedExpandoObject(
    {
      copyright: ['copyright', optional(string())],
      date: ['date', optional(string())],
      location: ['location', optional(locationSchema)],
      panoId: ['pano_id', optional(string())],
      status: ['status', streetViewStatusSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
