/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StreetViewStatus
 */
export enum StreetViewStatus {
  Ok = 'OK',
  InvalidRequest = 'INVALID_REQUEST',
  NotFound = 'NOT_FOUND',
  ZeroResults = 'ZERO_RESULTS',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
}

/**
 * Schema for StreetViewStatus
 */
export const streetViewStatusSchema: Schema<StreetViewStatus> = stringEnum(
  StreetViewStatus
);
