/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object containing a numeric value and its formatted text representation. */
export interface TextValueObject {
  /** String value. */
  text: string;
  /** Numeric value. */
  value: number;
  additionalProperties?: Record<string, unknown>;
}

export const textValueObjectSchema: Schema<TextValueObject> = typedExpandoObject(
  { text: ['text', string()], value: ['value', number()] },
  'additionalProperties',
  optional(unknown())
);
