/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TimeZoneStatus
 */
export enum TimeZoneStatus {
  Ok = 'OK',
  InvalidRequest = 'INVALID_REQUEST',
  OverDailyLimit = 'OVER_DAILY_LIMIT',
  OverQueryLimit = 'OVER_QUERY_LIMIT',
  RequestDenied = 'REQUEST_DENIED',
  UnknownError = 'UNKNOWN_ERROR',
  ZeroResults = 'ZERO_RESULTS',
}

/**
 * Schema for TimeZoneStatus
 */
export const timeZoneStatusSchema: Schema<TimeZoneStatus> = stringEnum(
  TimeZoneStatus
);
