/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** An object containing Unix time, a time zone, and its formatted text representation. */
export interface TimeZoneTextValueObject {
  /** The time specified as a string in the time zone. */
  text: string;
  /** The time specified as Unix time, or seconds since midnight, January 1, 1970 UTC. */
  value: number;
  /** Contains the time zone. The value is the name of the time zone as defined in the [IANA Time Zone Database](http://www.iana.org/time-zones), e.g. "America/New_York". */
  timeZone: string;
  additionalProperties?: Record<string, unknown>;
}

export const timeZoneTextValueObjectSchema: Schema<TimeZoneTextValueObject> = typedExpandoObject(
  {
    text: ['text', string()],
    value: ['value', number()],
    timeZone: ['time_zone', string()],
  },
  'additionalProperties',
  optional(unknown())
);
