/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TrafficModel1
 */
export enum TrafficModel1 {
  BestGuess = 'best_guess',
  Pessimistic = 'pessimistic',
  Optimistic = 'optimistic',
}

/**
 * Schema for TrafficModel1
 */
export const trafficModel1Schema: Schema<TrafficModel1> = stringEnum(
  TrafficModel1
);
