/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TrafficModel
 */
export enum TrafficModel {
  BestGuess = 'best_guess',
  Pessimistic = 'pessimistic',
  Optimistic = 'optimistic',
}

/**
 * Schema for TrafficModel
 */
export const trafficModelSchema: Schema<TrafficModel> = stringEnum(
  TrafficModel
);
