/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransitRoutingPreference
 */
export enum TransitRoutingPreference {
  LessWalking = 'less_walking',
  FewerTransfers = 'fewer_transfers',
}

/**
 * Schema for TransitRoutingPreference
 */
export const transitRoutingPreferenceSchema: Schema<TransitRoutingPreference> = stringEnum(
  TransitRoutingPreference
);
