/**
 * Google Maps PlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransitRoutingPreference1
 */
export enum TransitRoutingPreference1 {
  LessWalking = 'less_walking',
  FewerTransfers = 'fewer_transfers',
}

/**
 * Schema for TransitRoutingPreference1
 */
export const transitRoutingPreference1Schema: Schema<TransitRoutingPreference1> = stringEnum(
  TransitRoutingPreference1
);
