/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TravelMode
 */
export enum TravelMode {
  Driving = 'DRIVING',
  Bicycling = 'BICYCLING',
  Transit = 'TRANSIT',
  Walking = 'WALKING',
}

/**
 * Schema for TravelMode
 */
export const travelModeSchema: Schema<TravelMode> = stringEnum(TravelMode);
