/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Units2
 */
export enum Units2 {
  Imperial = 'imperial',
  Metric = 'metric',
}

/**
 * Schema for Units2
 */
export const units2Schema: Schema<Units2> = stringEnum(Units2);
