/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Units
 */
export enum Units {
  Imperial = 'imperial',
  Metric = 'metric',
}

/**
 * Schema for Units
 */
export const unitsSchema: Schema<Units> = stringEnum(Units);
