/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Units1
 */
export enum Units1 {
  Imperial = 'imperial',
  Metric = 'metric',
}

/**
 * Schema for Units1
 */
export const units1Schema: Schema<Units1> = stringEnum(Units1);
