/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VehicleType
 */
export enum VehicleType {
  Bus = 'BUS',
  CableCar = 'CABLE_CAR',
  CommuterTrain = 'COMMUTER_TRAIN',
  Ferry = 'FERRY',
  Funicular = 'FUNICULAR',
  GondolaLift = 'GONDOLA_LIFT',
  HeavyRail = 'HEAVY_RAIL',
  HighSpeedTrain = 'HIGH_SPEED_TRAIN',
  IntercityBus = 'INTERCITY_BUS',
  LongDistanceTrain = 'LONG_DISTANCE_TRAIN',
  MetroRail = 'METRO_RAIL',
  Monorail = 'MONORAIL',
  Other = 'OTHER',
  Rail = 'RAIL',
  ShareTaxi = 'SHARE_TAXI',
  Subway = 'SUBWAY',
  Tram = 'TRAM',
  Trolleybus = 'TROLLEYBUS',
}

/**
 * Schema for VehicleType
 */
export const vehicleTypeSchema: Schema<VehicleType> = stringEnum(VehicleType);
