/**
 * GoogleMapsPlatform
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Attributes used to describe a WiFi access point. */
export interface WiFiAccessPoint {
  /** The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon). */
  macAddress: string;
  /** The current signal strength measured in dBm. */
  signalStrength?: number;
  /** The current signal to noise ratio measured in dB. */
  signalToNoiseRatio?: number;
  /** The number of milliseconds since this access point was detected. */
  age?: number;
  /** The channel over which the client is communication with the access point. */
  channel?: number;
  additionalProperties?: Record<string, unknown>;
}

export const wiFiAccessPointSchema: Schema<WiFiAccessPoint> = typedExpandoObject(
  {
    macAddress: ['macAddress', string()],
    signalStrength: ['signalStrength', optional(number())],
    signalToNoiseRatio: ['signalToNoiseRatio', optional(number())],
    age: ['age', optional(number())],
    channel: ['channel', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
